version: "3."

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql

  wp:
    build: .
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      WORDPRESS_DB_NAME: wordpress
      # (opcional) sobrescreva via .env
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-}
      # (opcional) alternativa simples:
      # WP_FORCE_DOMAIN: site.exemplo.com
    ports:
      - "8080:80"
    volumes:
      - wp:/var/www/html

volumes:
  wp:
  db:
